import MuiWrapper from '@/MuiWrapper';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { SpeedInsights } from '@vercel/speed-insights/next';
import type { Metadata } from 'next';
import type { ReactNode } from 'react';
import './global.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const loadColorScheme = () => {
  const root = document.documentElement;
  const json = localStorage.getItem('mui-mode');
  let mode = 'light';
  if (json == null || json === 'system') {
    const mql = window.matchMedia('(prefers-color-scheme: dark)');
    if (mql.matches) mode = 'dark';
  } else {
    if (json === 'dark') mode = 'dark';
  }
  root.removeAttribute('data-dark');
  root.removeAttribute('data-light');
  root.setAttribute(`data-${mode}`, '');
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <script
            // biome-ignore lint/security/noDangerouslySetInnerHtml: ignore here
            dangerouslySetInnerHTML={{
              __html: `(${loadColorScheme.toString()})()`,
            }}
          />
          <MuiWrapper>
            <main className={'AppRoot'}>{children}</main>
          </MuiWrapper>
        </AppRouterCacheProvider>
        {process.env.NODE_ENV === 'production' && <SpeedInsights />}
      </body>
    </html>
  );
}
